services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Asylum29\TestBundle\Services\Hello:
        class: Asylum29\TestBundle\Services\Hello

    Asylum29\TestBundle\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
